### ISSUE TITLE
"sed: unmatched '/'" stops the installation.

### ISSUE THREAD

**Issue by Shamanni** [openlumi/homeassistant_on_openwrt#42]
> wget https://raw.githubusercontent.com/openlumi/homeassistant_on
_openwrt/23.05/ha_install.sh -O - | sh
Downloading 'https://raw.githubusercontent.com/openlumi/homeassistant_on_openwrt/23.05/ha_install.sh'
Connecting to 185.199.109.133:443
Writing to stdout
-                    100% |*******************************| 24469   0:00:00 ETA
Download completed (24469 bytes)
==========================================
 Installing Home Assistant 2024.2.1 ...
==========================================
Install base requirements from feed...
Downloading https://downloads.openwrt.org/releases/23.05.0/targets/ramips/mt7621/packages/Packages.gz
Updated list of available packages in /usr/lib/opkg/lists/openwrt_core
Downloading https://downloads.openwrt.org/releases/23.05.0/targets/ramips/mt7621/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/base/Packages.gz
Updated list of available packages in /usr/lib/opkg/lists/openwrt_base
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/luci/Packages.gz
Updated list of available packages in /usr/lib/opkg/lists/openwrt_luci
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/packages/Packages.gz
Updated list of available packages in /usr/lib/opkg/lists/openwrt_packages
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/routing/Packages.gz
Updated list of available packages in /usr/lib/opkg/lists/openwrt_routing
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/telephony/Packages.gz
Updated list of available packages in /usr/lib/opkg/lists/openwrt_telephony
Downloading https://downloads.openwrt.org/releases/23.05.0/packages/mipsel_24kc/telephony/Packages.sig
Signature check passed.
Detected Python 3.11
Package python3-base (3.11.7-1) installed in root is up to date.
Package python3-pynacl (1.5.0-3) installed in root is up to date.
Package python3-ciso8601 (2.3.0-1) installed in root is up to date.
Package patch (2.7.6-7) installed in root is up to date.
Package unzip (6.0-8) installed in root is up to date.
Package libjpeg-turbo (2.1.4-2) installed in root is up to date.
Package python3-aiohttp (3.8.5-1) installed in root is up to date.
Package python3-aiohttp-cors (0.7.0-2) installed in root is up to date.
Package python3-async-timeout (4.0.2-1) installed in root is up to date.
Package python3-asyncio (3.11.7-1) installed in root is up to date.
Package python3-attrs (23.1.0-1) installed in root is up to date.
Package python3-bcrypt (4.0.1-1) installed in root is up to date.
Package python3-boto3 (1.28.7-1) installed in root is up to date.
Package python3-botocore (1.31.7-1) installed in root is up to date.
Package python3-certifi (2023.7.22-1) installed in root is up to date.
Package python3-cffi (1.16.0-1) installed in root is up to date.
Package python3-cgi (3.11.7-1) installed in root is up to date.
Package python3-cgitb (3.11.7-1) installed in root is up to date.
Package python3-chardet (5.1.0-1) installed in root is up to date.
Package python3-codecs (3.11.7-1) installed in root is up to date.
Package python3-cryptodome (3.18.0-1) installed in root is up to date.
Package python3-cryptodomex (3.18.0-1) installed in root is up to date.
Package python3-cryptography (41.0.7-1) installed in root is up to date.
Package python3-ctypes (3.11.7-1) installed in root is up to date.
Package python3-dateutil (2.8.2-2) installed in root is up to date.
Package python3-dbm (3.11.7-1) installed in root is up to date.
Package python3-decimal (3.11.7-1) installed in root is up to date.
Package python3-defusedxml (0.7.1-1) installed in root is up to date.
Package python3-distutils (3.11.7-1) installed in root is up to date.
Package python3-docutils (0.20.1-1) installed in root is up to date.
Package python3-email (3.11.7-1) installed in root is up to date.
Package python3-greenlet (2.0.2-1) installed in root is up to date.
Package python3-idna (3.4-1) installed in root is up to date.
Package python3-jinja2 (3.1.2-1) installed in root is up to date.
Package python3-jmespath (1.0.1-1) installed in root is up to date.
Package python3-light (3.11.7-1) installed in root is up to date.
Package python3-logging (3.11.7-1) installed in root is up to date.
Package python3-lzma (3.11.7-1) installed in root is up to date.
Package python3-markupsafe (2.1.3-1) installed in root is up to date.
Package python3-multidict (6.0.4-1) installed in root is up to date.
Package python3-multiprocessing (3.11.7-1) installed in root is up to date.
Package python3-ncurses (3.11.7-1) installed in root is up to date.
Package python3-netdisco (3.0.0-1) installed in root is up to date.
Package python3-netifaces (0.11.0-1) installed in root is up to date.
Package python3-openssl (3.11.7-1) installed in root is up to date.
Package python3-pillow (9.5.0-2) installed in root is up to date.
Package python3-pip (23.2.1-1) installed in root is up to date.
Package python3-pkg-resources (68.2.2-1) installed in root is up to date.
Package python3-ply (3.11-2) installed in root is up to date.
Package python3-psutil (5.9.5-1) installed in root is up to date.
Package python3-pycparser (2.21-2) installed in root is up to date.
Package python3-pydoc (3.11.7-1) installed in root is up to date.
Package python3-pyopenssl (23.2.0-1) installed in root is up to date.
Package python3-pytz (2023.3-1) installed in root is up to date.
Package python3-requests (2.30.0-1) installed in root is up to date.
Package python3-s3transfer (0.6.1-1) installed in root is up to date.
Package python3-setuptools (68.2.2-1) installed in root is up to date.
Package python3-six (1.16.0-1) installed in root is up to date.
Package python3-slugify (8.0.1-1) installed in root is up to date.
Package python3-sqlalchemy (2.0.20-1) installed in root is up to date.
Package python3-sqlite3 (3.11.7-1) installed in root is up to date.
Package python3-unittest (3.11.7-1) installed in root is up to date.
Package python3-urllib (3.11.7-1) installed in root is up to date.
Package python3-urllib3 (2.0.4-1) installed in root is up to date.
Package python3-xml (3.11.7-1) installed in root is up to date.
Package python3-yaml (6.0.1-1) installed in root is up to date.
Package python3-yarl (1.9.2-1) installed in root is up to date.
Unknown package 'python3-gdbm'.
Package python3-pycares (4.3.0-2) installed in root is up to date.
Unknown package 'python3-numpy'.
find: /usr/lib/python3.11/site-packages/numpy: No such file or directory
Install base requirements from PyPI...
Requirement already satisfied: wheel in /usr/lib/python3.11/site-packages (0.42.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: aioesphomeapi==21.0.2 in /usr/lib/python3.11/site-packages (from -r /tmp/requirements_nodeps.txt (line 1)) (21.0.2)
Requirement already satisfied: esphome-dashboard-api==1.2.3 in /usr/lib/python3.11/site-packages (from -r /tmp/requirements_nodeps.txt (line 2)) (1.2.3)
Requirement already satisfied: zeroconf==0.131.0 in /usr/lib/python3.11/site-packages (from -r /tmp/requirements_nodeps.txt (line 3)) (0.131.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
sed: unmatched '/'

**Comment by devbis** [comment]
Thanks for the bug report. The script is fixed, please, run again

**Comment by tmn505** [comment]
I think You forgot to push changes, https://github.com/openlumi/homeassistant_on_openwrt/blob/23.05/ha_install.sh#L176 is still missing ` /` before last apostrophe in `-e 's/chacha20poly1305-reuseable \(.*\)/chacha20poly1305-reuseable >=0.10.0'`.

**Comment by devbis** [comment]
Ahhhh, push failed, Yes, you're right. Now it it fixed for real
